<?php declare(strict_types=1); ?>
<!doctype html>
<html lang="pl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AI Orchestra — Twoja muzyka</title><link rel="stylesheet" href="/assets/css/style.css"></head><body>
<header class="site-header"><a class="brand" href="/"><span class="brand-mark">◈</span> AI <strong>ORCHESTRA</strong></a><nav aria-label="Nawigacja"><a class="active" href="/">Studio</a><a href="/piano">Pianino</a><a href="/guitar">Gitara</a></nav><span class="local"><i></i> LOKALNE STUDIO</span></header>
<main><section class="hero"><div class="hero-shade"></div><div class="hero-copy"><span class="eyebrow">— TWOJA MUZYKA. TWOJE ZASADY.</span><h1>Muzyka zaczyna się<br>od <em>Twojej wizji.</em></h1><p>Zapisz utwór w kodzie, kształtuj każdą nutę i pozwól cyfrowej orkiestrze go wykonać. Pełna kontrola nad kompozycją — od pierwszego dźwięku po ostatni akord.</p><div class="actions"><a class="button" href="/piano">Odkryj pianino <span>↗</span></a><a class="link" href="/guitar">Odkryj gitarę ↗</a><a class="link" href="#idea">Jak to działa ↓</a></div><a class="mixer-entry" href="/mixer"><span class="mixer-entry-icon">≋</span><span><small>POŁĄCZ GOTOWE ŚCIEŻKI</small><strong>Otwórz mikser muzyczny</strong></span><b>↗</b></a></div><small class="photo-caption">01 / PIANINO KONCERTOWE</small></section>
<section class="intro" id="idea"><div><span class="eyebrow">NOWY SPOSÓB TWORZENIA</span><h2>Komponuj świadomie.<br><em>Słuchaj bez ograniczeń.</em></h2></div><p>AI Orchestra opiera się na czytelnej partyturze JSON. To Ty określasz wysokość, czas, dynamikę i instrument. Aplikacja przygotowuje wykonanie, zachowując Twoje decyzje w centrum procesu.</p></section>
<section class="cards" aria-label="Założenia projektu"><article><span class="number">01</span><span class="icon">♫</span><h3>Każda nuta ma znaczenie</h3><p>Twórz i poprawiaj konkretne dźwięki bez zgadywania, co wygeneruje system.</p></article><article><span class="number">02</span><span class="icon">{ }</span><h3>Partytura jako kod</h3><p>Utwór zapisany w JSON jest czytelny, wersjonowalny i gotowy do dalszej pracy.</p></article><article><span class="number">03</span><span class="icon">◎</span><h3>Wszystko u Ciebie</h3><p>Projekt działa lokalnie. Twoje pomysły i pliki pozostają na Twoim komputerze.</p></article></section>
<section class="library"><div><span class="eyebrow">TWOJA PRZESTRZEŃ</span><h2>Biblioteka utworów</h2><p>Pierwsze kompozycje pojawią się tu, gdy dodamy edytor partytury.</p></div><div class="library-box"><?php if ($songs === []): ?><span class="icon">♩</span><strong>Tu zacznie się Twoja historia</strong><span>Biblioteka jest na razie pusta.</span><?php else: ?><ul><?php foreach ($songs as $song): ?><li><?= htmlspecialchars($song, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8') ?></li><?php endforeach; ?></ul><?php endif; ?></div></section></main>
<footer>AI ORCHESTRA <span>/</span> LOKALNE STUDIO MUZYCZNE <span class="footer-right">Kompozycja należy do Ciebie.</span></footer></body></html>
