<?php declare(strict_types=1); ?>
<!doctype html><html lang="pl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Pianino — AI Orchestra</title><link rel="stylesheet" href="/assets/css/style.css"><script src="/assets/js/piano.js" defer></script></head><body>
<header class="site-header"><a class="brand" href="/"><span class="brand-mark">◈</span> AI <strong>ORCHESTRA</strong></a><nav aria-label="Nawigacja"><a href="/">Studio</a><a class="active" href="/piano">Pianino</a><a href="/guitar">Gitara</a></nav><span class="local"><i></i> LOKALNE STUDIO</span></header>
<main><section class="hero piano-hero"><div class="hero-shade"></div><div class="hero-copy"><span class="eyebrow">— INSTRUMENT 01 / KLAWISZOWE</span><h1>Pianino</h1><p>Od pojedynczego dźwięku do pełnej harmonii. Poznaj instrument, od którego zaczyna się Twoja orkiestra.</p><a class="link" href="#klawiatura">Przejdź do klawiatury ↓</a></div><small class="photo-caption">PIANINO KONCERTOWE · STUDIUM ŚWIATŁA</small></section>
<section class="intro"><div><span class="eyebrow">PRECYZJA I EKSPRESJA</span><h2>Twoje palce.<br><em>Twoje brzmienie.</em></h2></div><p>Sprawdź dźwięki na klawiaturze poniżej. To prosty podgląd syntetyczny w przeglądarce; później dołączymy edytor partytury i lokalny renderer pianina.</p></section>
<section class="keyboard-section" id="klawiatura"><div class="keyboard-heading"><div><span class="eyebrow">INTERAKTYWNY PODGLĄD</span><h2>Klawiatura</h2></div><label>Głośność <output id="volume-value">40%</output> <input id="volume" type="range" min="0" max="100" value="40"></label></div><p>Kliknij klawisz lub użyj klawiatury komputera: A S D F G H J K oraz W E T Y U.</p><div class="keyboard-scroll"><div class="keyboard" id="piano-keyboard" aria-label="Klawiatura pianina"></div></div><p id="note-status" aria-live="polite">Wybierz nutę, aby usłyszeć dźwięk.</p></section>
<section class="next"><div><span class="eyebrow">NASTĘPNY ETAP</span><h2>Od dźwięku do partytury</h2><p>Ta strona jest pierwszą warstwą instrumentu. Docelowo parametry nut, dynamika i wykonanie będą zapisane w <code>song.json</code>.</p></div><a class="button outline" href="/">Wróć do studia ↗</a></section>
<section class="score-render" aria-labelledby="score-render-heading"><div><span class="eyebrow">PARTYTURA → AUDIO</span><h2 id="score-render-heading">Posłuchaj zapisu JSON</h2><p>Wybierz partyturę pianina z biblioteki i wygeneruj plik WAV. Wysokości nut, czas i dynamika są odczytywane z wybranego JSON. Wybierz brzmienie fortepianu próbkowanego albo dotychczasowy podgląd syntetyczny.</p></div><div class="render-panel"><label class="score-label" for="score-file">Dostępne partytury pianina</label><?php if ($pianoScores !== []): ?><select id="score-file" class="score-select"><?php foreach ($pianoScores as $fileName => $scoreInfo): ?><option value="<?= htmlspecialchars($fileName, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8') ?>"><?= htmlspecialchars($fileName . ' · ' . $scoreInfo['title'] . ' (' . $scoreInfo['notes'] . ' nut)', ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8') ?></option><?php endforeach; ?></select><?php else: ?><p>Brak partytur z instrumentem pianina w <code>app/library</code>.</p><?php endif; ?><label class="score-label" for="render-engine">Brzmienie</label><select id="render-engine" class="score-select"><option value="sampled">YDP Grand Piano · koncertowy (Python)</option><option value="upright-kw">Kawai Upright KW · pianino stojące (Python)</option><option value="synthetic">Podgląd syntetyczny · przeglądarka</option></select><div class="hand-balance"><label for="hand-balance">Balans rąk <output id="hand-balance-value">Równowaga</output></label><input id="hand-balance" type="range" min="-100" max="100" step="5" value="0"><div class="balance-ends"><span>← Tylko lewa</span><span>Tylko prawa →</span></div><small>Środek wyrównuje średnią dynamikę obu rąk. Po zmianie gotowy odsłuch i WAV aktualizują się automatycznie.</small></div><div class="output-level"><label for="output-gain">Poziom końcowego WAV <output id="output-gain-value">0 dB</output></label><input id="output-gain" type="range" min="-12" max="12" step="1" value="0"><div class="balance-ends"><span>−12 dB · ciszej</span><span>+12 dB · głośniej</span></div><p id="level-warning" class="level-warning" role="status" aria-live="polite">Analizuję poziom wybranej partytury…</p><small>Ocena zależy od utworu, modelu i balansu. Eksport ogranicza szczyt do około −1 dBFS, aby uniknąć nowego przesterowania.</small></div><button class="button" id="render-score" type="button"<?= $pianoScores === [] ? ' disabled' : '' ?>>Generuj plik WAV <span>↗</span></button><p id="render-status" role="status" aria-live="polite">Plik audio powstaje lokalnie w projekcie.</p><audio id="render-preview" controls hidden></audio><a id="render-download" class="link" download="piano.wav" hidden>Pobierz plik WAV ↓</a><small>YDP Grand Piano: Zenph Studios / FreePats, CC BY 3.0. Kawai Upright KW: Gonzalo i Roberto / FreePats, CC0 1.0.</small></div></section></main>
<script src="/assets/js/render-piano.js" defer></script>
<footer>AI ORCHESTRA <span>/</span> PIANINO <span class="footer-right">Kompozycja należy do Ciebie.</span></footer></body></html>
