<?php declare(strict_types=1); ?>
<!doctype html>
<html lang="pl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Skrzypce — AI Orchestra</title><link rel="stylesheet" href="/assets/css/style.css"><script src="/assets/js/violin.js" defer></script><script src="/assets/js/render-violin.js" defer></script></head><body>
<header class="site-header"><a class="brand" href="/"><span class="brand-mark">◈</span> AI <strong>ORCHESTRA</strong></a><nav aria-label="Nawigacja"><a href="/">Studio</a><a href="/piano">Pianino</a><a href="/guitar">Gitara</a><a class="active" href="/violin">Skrzypce</a><a href="/mixer">Mikser</a></nav><span class="local"><i></i> LOKALNE STUDIO</span></header>
<main><section class="hero violin-hero"><div class="hero-shade"></div><div class="hero-copy"><span class="eyebrow">— INSTRUMENT 03 / SMYCZKOWE</span><h1>Skrzypce</h1><p>Jedna linia melodyczna, nieskończenie wiele odcieni. Kontroluj wysokość, czas i dynamikę, a cyfrowy smyczek nada zapisowi głos.</p><a class="link" href="#fingerboard">Przejdź do gryfu ↓</a></div><small class="photo-caption">SKRZYPCE SOLO · STUDIUM ŚWIATŁA</small></section>
<section class="intro"><div><span class="eyebrow">OD SMYCZKA DO FRAZY</span><h2>Dźwięk prowadzony.<br><em>Świadoma ekspresja.</em></h2></div><p>Interaktywny gryf korzysta z przewidywalnej syntezy w przeglądarce. Eksport partytury może użyć tego samego prototypu albo próbek skrzypiec FreePats renderowanych lokalnie przez Python i FluidSynth.</p></section>
<section class="violin-section" id="fingerboard"><div class="keyboard-heading"><div><span class="eyebrow">INTERAKTYWNY PODGLĄD</span><h2>Gryf skrzypiec</h2></div><label>Głośność <output id="violin-volume-value">35%</output><input id="violin-volume" type="range" min="0" max="100" value="35"></label></div><p>Naciśnij pozycję i przytrzymaj, aby prowadzić syntetyczny dźwięk smyczka. Cztery struny są strojone G3–D4–A4–E5.</p><div class="violin-board" id="violin-board" aria-label="Interaktywny gryf skrzypiec"></div><p id="violin-note-status" role="status" aria-live="polite">Wybierz strunę i pozycję.</p></section>
<section class="score-render" aria-labelledby="violin-render-heading"><div><span class="eyebrow">PARTYTURA → AUDIO</span><h2 id="violin-render-heading">Posłuchaj skrzypiec z JSON</h2><p>Wybierz partyturę i porównaj model próbkowany z syntezą. Nuty, tempo i velocity zawsze pochodzą z tego samego pliku MusicJSON.</p></div><div class="render-panel"><label class="score-label" for="violin-score-file">Dostępne partytury skrzypiec</label><?php if ($violinScores !== []): ?><select id="violin-score-file" class="score-select"><?php foreach ($violinScores as $fileName => $scoreInfo): ?><option value="<?= htmlspecialchars($fileName, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8') ?>"><?= htmlspecialchars($fileName . ' · ' . $scoreInfo['title'] . ' (' . $scoreInfo['notes'] . ' nut)', ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8') ?></option><?php endforeach; ?></select><?php else: ?><p>Brak partytur skrzypiec w <code>app/library</code>.</p><?php endif; ?><label class="score-label" for="violin-render-engine">Brzmienie WAV</label><select id="violin-render-engine" class="score-select"><option value="sampled">Skrzypce FreePats · próbki SF2</option><option value="synthetic">Skrzypce syntetyczne · przeglądarka</option></select><button class="button" id="render-violin" type="button"<?= $violinScores === [] ? ' disabled' : '' ?>>Generuj plik WAV <span>↗</span></button><p id="violin-render-status" role="status" aria-live="polite">Audio powstaje lokalnie.</p><audio id="violin-render-preview" controls hidden></audio><a id="violin-render-download" class="link" download="violin.wav" hidden>Pobierz plik WAV ↓</a><small>FreePats General MIDI 2022-10-26: GPL 3+ ze specjalnym wyjątkiem. Model syntetyczny jest prostym prototypem smyczka.</small></div></section>
<section class="next"><div><span class="eyebrow">NASTĘPNY ETAP</span><h2>Artykulacja zapisana<br><em>w partyturze.</em></h2><p>Obecny silnik realizuje wysokość, czas, tempo i dynamikę. Kolejne modele mogą rozdzielić legato, détaché, staccato oraz vibrato bez zmiany strony instrumentu.</p></div><a class="button outline" href="/mixer">Przejdź do miksera ↗</a></section></main>
<footer>AI ORCHESTRA <span>/</span> SKRZYPCE <span class="footer-right">Kompozycja należy do Ciebie.</span></footer></body></html>
